cuqueue/urls.py
from . import views
from django.conf.urls import url,include
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^Token',views.get_data,name="Token"),
    url(r'^reset',views.reset,name='reset'),
    url(r'^login',views.login_page,name='login'),
    url(r'^staff',views.staff,name='staff'),
    url(r'^', include('django.contrib.auth.urls')),

    # url(r'^list',views.lists,name='list'),
]

untitled/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('cuqueue.urls')),
]

cuqueue/models.py
from django.db import models


class detail(models.Model):

    name=models.CharField(max_length=30)
    uid=models.CharField(max_length=30)
    mobile_no=models.BigIntegerField()
    email = models.EmailField(max_length=30)
    time=models.DateTimeField(auto_now=True)
    given_time=models.TimeField(auto_now=False)
    lineno=models.BigIntegerField()
    QR=models.ImageField()
    def __str__(self):
        return str(self.pk) + '.' +" "+  self.name

cuqueue/forms.py
from django import forms
from .models import detail
from django.utils.safestring import mark_safe
class NameForm(forms.ModelForm):
    name=forms.CharField(label=mark_safe("<br/>Name"),max_length=30)
    uid = forms.CharField(label=mark_safe("<br/>UID"),max_length=30)
    mobile_no = forms.IntegerField(label=mark_safe("<br/>Mobile No."))
    email = forms.EmailField(label=mark_safe("<br/>Email ID"),max_length=30)

    class Meta:
        model= detail

        fields=('name','uid','mobile_no','email',)

class staffform(forms.Form):
    username=forms.CharField(label=mark_safe("<br/>Username"),max_length=30)
    password=forms.CharField(widget=forms.PasswordInput(render_value=True))

cuqueue/views.py
from django.shortcuts import render, redirect
from .forms import NameForm,staffform
from django.urls import reverse
from django.core.mail import send_mail
from cuqueue.models import detail
import datetime
from django.contrib.auth import authenticate,login
from django.contrib import messages
import random,string
import pyqrcode
import numpy as np
import pandas as pd


min_ch=0
q_no=0
hrs=8
def qrcode(token,name):
    q=pyqrcode.create(token)
    q.png("cuqueue/static/pics/%s.png"%name,scale=6)
    return '%s.png'%name

def index(request):
    form = NameForm()
    return render(request, "cuqueue/home.html", {"form": form})


def get_data(request):
    global min_ch, q_no,hrs
    if min_ch>59:
        hrs+=1
        min_ch=0
    q_no += 1
    min_ch = min_ch + 5
    to_give_time = datetime.datetime.now()
    to_give_time = to_give_time.replace(hour=hrs, minute=min_ch, second=0, microsecond=0)
    form = NameForm(request.POST)
    save_it = form.save(commit=False)
    save_it.check=False
    save_it.given_time = to_give_time
    save_it.lineno = q_no
    subject = "Token Number"
    random_token=''.join(random.choice(string.ascii_lowercase+string.ascii_uppercase+string.digits)for _ in range(10))
    message = "Your Token Number is:" + random_token
    from_email = 'cucoderarmy@gmail.com'
    save_it.QR=qrcode(random_token,save_it.name)
    messages.success(request,'%s.png'%save_it.name)

    to_email = [save_it.email, from_email]
    send_mail(subject, message, from_email, to_email)
    save_it.save()
    return redirect(reverse("index"))


def lists(request):
    get_it = detail.objects.all()
    return render(request, "cuqueue/list.html", {"get_it": get_it})

def login_page(request):
    form=staffform()
    password_reset='password_reset'
    return render(request,"cuqueue/staff_login.html",{'form':form,'password_reset':password_reset})

def staff(request):
    username=request.POST['username']
    password=request.POST['password']
    user=authenticate(request,username=username,password=password)
    if user is not None:
        login(request,user)
        return lists(request)

    else:
        return redirect(reverse('login'))

def reset(request):
    global min_ch,q_no
    data = detail.objects.all()
    data.delete()
    return redirect('index')

templates/cuqueue/home.html
<!doctype html>
<html>
	<head>
	    <title>VIRTUAL QUEUE</title>

		<link rel="stylesheet" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/background.css">
        <link rel="stylesheet" type="text/css" href="/static/css/csshake.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     </head>
		<body>
		    <div class="looks"></div>
			<header>
			    <div><img  src="/static/chandigarh-university-seal.png"  style='width:40%;' border="0" alt="Null"></div>
				    <div class="container">
				        <h1 class="titlebar col-xl-12">VIRTUAL QUEUE
				        </h1>
				            <div class="second_title">
			            <div class="home">A Comfortable Way to be in Queue</div>
		            </div>
		         </div>
			</header>
            <div class="container">
				<form action="Token"  method="post">
                   		<div class="form-group">
                   			<div class="Name">
                   			    <label for="exampleInputName">Name:</label>
                   			        <input name="name" type="text" class="form-control" id="id_name" placeholder="Enter Name" required="" maxlength="30">
							         {% csrf_token %}
						   </div>
						    <div class="UID">
							     <label for="exampleInputUID">UID:</label>
							        <input name="uid" type="text" class="form-control" id="id_uid" placeholder="Enter UID" required="" maxlength="9">
							            {% csrf_token %}
							  </div>
							  <div class="MobileNumber">
							    <label for="exampleInputNumber">Mobile Number:</label>
							        <input name="mobile_no" type="tel" class="form-control" id="id_mobile_no" placeholder="Where to Contact" required="" maxlength="11"  pattern="^\d{4}\d{3}\d{4}$" required >
							    	    {% csrf_token %}
							   </div>
							    <div class="Email">
                   			        <label for="exampleInputEmail">Email:</label>
                   			            <input name="email" type="email" class="form-control" id="id_email" placeholder="your@email.com" required="" maxlength="30">
							                {% csrf_token %}
							  	</div>
					     </div>
					 <div class="btn">
        			  	<div class="shake-rotate">
        			  	  <button id="myBtn" type="submit" style= "padding-right:10px;display:block;" value="submit">
                            Create Token
        			  	   </button>
                        </div>
                     </div>
        			  	   	</form>
                        </div>
        </body>

				<div id="myModal" class="modal">
				  <div class="modal-content">
				    <div class="modal-body">
				        <div class="notify successbox">
                            <h1>Success!</h1>
                            <h2>Your tokken is</h2>
                        <p>
                            {%for message in messages%}
				             <img src="/static/pics/{{message}}" height="70%" width="70%" hspace="40">
				             {%endfor%}
                        </p>
                      </div>
                      <div class="fbtn" >
                        <button class="container" id="mybtn1" style="width:75%;">
                                OKAY
                            </button>
                      </div>
                      </div>
				   </div>
				  </div>
				  <div class="container col-lg-12 col-sm-12">
                        <div class="container-fluid" style="padding-top:10px;">
                          <h1 style="font-family:TimesNewRoman; text-shadow:4px #fff">GET IN TOUCH</h1>
                          <div class="row" style="background-color:lavender;">
                               <div class="carddesign col-xs-1 col-sm-2 col-lg-2" style="padding-top:10px">
                    				<div class='card card-profile text-center'>
                                      <img alt='' class='card-img-top' src='https://unsplash.it/340/160?image=354'>
                                      <div class='card-block'>
                                        <img alt='' class='card-img-profile' src='/static/PicsArt_03-25-04.39.26.jpeg'>
                                        <h4 class='card-title'>
                                          Harnoor Singh
                                          <small><br>Front-end designer</small>
                                        </h4>
                                        <div class='card-links'>
                                          <a class='fa fa-github' href='https://github.com/Harnoor6693'></a>
                                          <a class='fa fa-linkedin' href='https://www.linkedin.com/in/harnoor-s-0209b0137/'></a>
                                          <a class='fa fa-facebook' href='https://www.facebook.com/harnoor.singh.10236'></a>
                                        </div>
                                      </div>
                                    </div>
                                </div>
                                <div class="carddesign1 col-xs-1 col-sm-2 col-lg-2" style="padding-top:10px">
                                    <div class='card card-profile text-center'>
                                      <img alt='' class='card-img-top' src='https://unsplash.it/340/160?image=354'>
                                         <div class='card-block'>
                                            <img alt='' class='card-img-profile' src='/static/150x150.png '>
                                                <h4 class='card-title'>
                                                    Karan Jakhar
                                                        <small>Back-end developer</small>
                                                 </h4>
                                            <div class='card-links' style="padding-bottom:7px;">
                                              <a class='fa fa-github' href='https://github.com/karanjakhar'></a>
                                              <a class='fa fa-linkedin' href='https://www.linkedin.com/in/karan-jakhar-365662149/'></a>
                                              <a class='fa fa-facebook' href='https://www.facebook.com/karan.jakhar.75'></a>
                                             </div>
                                          </div>
                                    </div>
                                 </div>
                                  <div class="carddesign2 col-xs-1 col-sm-8 col-lg-8" style="padding-top:10px; background:white">
                                    <div class='card card-profile text-left' style="background:#333; color:#fff;padding-top:10px;padding-left:10px">
                                        <p calss="container-fluid" style="font-family:Open Sans;">
                                                <b>Mob:</b> 7009770701
                                                <br><b>Email:</b><a href="mailto:noorsingh6693@gmail.com"> noorsingh6693@gmail.com</a></br>
                                                <b>Mob:</b> 9646266873
                                                <br><b>Email:</b><a href="mailto:karanjakhar4@gmail.com"> karanjakhar4@gmail.com</a></br>
                                                <br>
                                                <a style="font-size:20px;letter-spacing:2px;font-weight: bold;text-decoration:underline;" href="http://www.cuchd.in/">Chandigarh University</a></br>
                                                NH-95 Chandigarh-Ludhiana Highway,<br>Mohali,Punjab (INDIA)</br>
                                                General Helpline No:+91-160-3051003
                                                <br>Toll Free: 1800 200 0025</br>
                                                <a style="letter-spacing:2px;" href="https://maps.google.com/maps?q=30.764314651489258%2C76.57359313964844&z=17&hl=en" style="">
                                                        <i class="fa fa-map-marker"></i>
                                                    <span>Open In Google Maps</span>
                                                </a>
                                        </p>
                                    </div>
                                 </div>
                          </div>
                      </div>
                    </div>
    {% csrf_token %}
    {% if  token %}
     {{ token }}

    {% endif %}
</body>
<script>
    var modal = document.getElementById('myModal');
    var btn = document.getElementById("myBtn");
        {%if messages%}
            {
                modal.style.display = "block";
            }
        {%endif%}
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
<script>
    var modal = document.getElementById('myModal');
    var btn1 = document.getElementById("mybtn1");
        btn1.onclick = function(event) {
            modal.style.display = "none";
        event.preventDefault();
    }
</script>
</html>

templates/cuqueue/list.html
<!doctype html>
<html>
	<head>
        <title>LIST</title>
		    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
            <link rel="stylesheet" href="/static/staff_background.css">
     </head>
		<body>
		    <div class="looks"></div>
			<header>
			    <div><img  src="/static/chandigarh-university-seal.png"></div>
				    <div class="container">
        				<h1 class="titlebar col-xl-12">
        				    VIRTUAL QUEUE
        				</h1>
			    	<div class="container">
			            <div class="home">A Comfortable Way to be in Queue</div>
		            </div>
                </div>
		  	</header>
            <div class="container">
                <main role="main" class="col-xl-12"></main>
                <h2 class="section">Today's List</h2>
            </div>
            <div class="container">
                <div class="list">
                    <table class="table table-striped ">
                        <thead>
                            <tr>
                                <th>Sr.No</th>
                                <th>Queue No.</th>
                                <th>Name</th>
                                <th>UID</th>
                                <th>Created Time</th>
                                <th>Given Time</th>
                                <th></th>
                                <th></th>
                                <th></th>
    			                </tr>
                        </thead>
            {% for i in get_it %}
            {% csrf_token %}

                        <tbody>
                            <tr>
                                <td>{{i.pk}}</td>
                                <td>{{i.lineno}}</td>
                                <td>{{i.name}}</td>
                                <td>{{i.uid}}</td>
                                <td>{{i.time}}</td>
                                <td>{{i.given_time}}</td>
                                <td><div class="col">
                                    <input type="number" class="form-control" placeholder="Amount">
                                </div></td>
                                <td><a href="" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Refund</a></td>
                                <td><a href="" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Pay</a></td>
                            </tr>
                        </tbody>

{% endfor %}
                  </table>
                </div>
            </div>
        <script src="/static/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    </body>
</html>

templates/cuqueue/staff_login.html
<!doctype html>
<html>
	<head>
	    <title>VIRTUAL QUEUE/Staff login</title>

		<link rel="stylesheet" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/staff_background.css">
     </head>
		<body>
		    <div class="looks"></div>
			<header>
			    <div><img  src="/static/chandigarh-university-seal.png"></div>
				    <div class="container">
				        <h1 class="titlebar col-xl-12">
				        VIRTUAL QUEUE
				        </h1>
                    </div>
				<div class="container">
				    <div class="second_title">
			            <div class="home">A Comfortable Way to be in Queue</div>
		             </div>
                </div>
			</header>
            <div class="container">
				<form action="staff"  method="post">
				     {% csrf_token %}
                   		<div class="form-group">
                   			<div class="User_Name">
                   			    <label for="exampleInputName">User Name:</label>
                   			    <input name="username" type="text" class="form-control" id="id_username" placeholder="Enter username" required="" maxlength="30">
                            </div>
                            <div class="Password">
							      <label for="exampleInputPassword">Password:</label>
                                  <input name="password" type="password" class="form-control" id="id_password" placeholder="Enter Password" required="" maxlength="30">
                            </div>
                            <button type="submit" class="btn btn-primary" style="padding:15px 50px; display:block; margin: 0 auto;">
                                Log in
                            </button>
                        </div>
                </form>
            </div>
            <a href="{% url password_reset %}">Forgot password?
        </a>
</body>
</html>